name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Verify the runner environment
      - name: Verify runner environment
        run: |
          echo "Checking installed tools..."
          which curl || echo "curl not found"
          which sh || echo "sh not found"
          which bash || echo "bash not found"
          echo "Environment PATH: $PATH"

      # Step 3: Install curl if missing
      - name: Install curl (if not installed)
        run: sudo apt-get update && sudo apt-get install -y curl

      # Step 4: Install Rust using actions-rs
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Step 5: Install Dojo Engine
      - name: Install Dojo Engine
        run: |
          curl -L https://install.dojoengine.org | bash
          echo "$HOME/.dojo/bin" >> $GITHUB_PATH

      # Step 6: Install Scarb
      - name: Install Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
          echo "$HOME/.scarb/bin" >> $GITHUB_PATH

      # Step 7: Build with Sozo
      - name: Build with Sozo
        run: sozo build

      # Step 8: Start Katana devnet in the background
      - name: Start Katana Devnet
        run: |
          nohup katana --dev --dev.no-fee > katana.log 2>&1 &
          sleep 10  # Wait for Katana to start

      # Step 9: Inspect using Sozo
      - name: Inspect with Sozo
        run: sozo inspect

      # Step 10: Upload Katana logs
      - name: Upload Katana Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: katana-logs
          path: katana.log
